### ISSUE TITLE
gui: unexpected exception: invalid interface name

### ISSUE THREAD

**Issue by jgibbon** [mkiol/kamkast#1]
Hi,
I've just tried the openrepos release and I am impressed!
Terminal mode works well (short screen sharing test on Xperia X only).

I have a problem starting with gui, though, it just exits on start:
`0xf3435000 operator():65 - unexpected exception: invalid interface name`

Combining --gui/-g with the arguments for interface/ip does not seem to make any difference.

But even from terminal/ssh, this is a really useful application – the web interface is a nice touch, as well!

cheers!

**Comment by mkiol** [comment]
Thanks for the report.

When program starts in gui mode (``--gui``) the configuration is loaded from a file (~/.config/org.mkiol/kamkast/settings.config). Could you please check what  the value of ``ifname`` is? By default it should be ``wlan``. 

I might wrongly assumed that every SFOS device has this interface or ``wlan`` is always up... which obviously is not right assumption :/

**Comment by mkiol** [comment]
the best is to set ``ifname`` to no value which means 'listen on all interfaces'

```
[general]
address=0.0.0.0
ifname=
port=9099
```

**Comment by jgibbon** [comment]
Oh yeah, I just rechecked. 
Indeed I have wifi switched off most of the time. GUI starts if it is on!

Sorry for not connecting (pun really not intended) the error with my habit of switching off wifi. At least I should've thought about mentioning USB network.

cheers

edit: after Setting the interface to All in GUI it indeed works with wifi disabled. 
So I think that would be a useful default value if you don't want to implement a "fallback to all" feature instead of the exception.

**Comment by mkiol** [comment]
Thank you for very sane suggestion 👍🏿
